//Chris Lucian & Chad Davies
//CS 643 Advanced Databases
//11/8/2014

using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using GameReviewWebsiteProject.Filters;
using GameReviewWebsiteProject.Models;

namespace GameReviewWebsiteProject.Controllers
{
    //Accounts controller manages the creation and login of new and existing users
    [Authorize]
    [InitializeSimpleMembership]
    public class AccountController : Controller
    {
        //This controller action displays thepage to login along with allowing for a redirect URL to be passed to the view
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        
        //This is the post action for the login allowing a user to log in with their credentials
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid && WebSecurity.Login(model.UserName, model.Password, persistCookie: model.RememberMe))
            {
                return RedirectToLocal(returnUrl);
            }

            ModelState.AddModelError("", "The user name or password provided is incorrect.");
            return View(model);
        }

        //This post action allows the user to log out
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            //WebSecurity is a built in library for MVC
            //Given a database connection in its configuration 
            WebSecurity.Logout();
            return RedirectToAction("Index", "GameReviews");
        }

        //Displays the page for a user to log in
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //Post action for a registering user
        //if a new user is created properly then they are allowed to log in and redirected back to the main page of the site
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CreateNewUser(model);
                    WebSecurity.Login(model.UserName, model.Password);
                    return RedirectToAction("Index", "GameReviews");
                }
                catch (MembershipCreateUserException e)
                {
                    ModelState.AddModelError("", ErrorCodeToString(e.StatusCode));
                }
            }

            return View(model);
        }

        //Insert statement to add a new user
        private static void CreateNewUser(RegisterModel model)
        {
            //Entity Framework classes generated by the database schema are used to insert into the database
            var db = new GameReviewWebsiteEntities();
            db.Gamers.Add(new Gamer()
                              {
                                  Biography = model.Bio,
                                  Name = model.UserName,
                                  Password = model.Password
                              });
            db.SaveChanges();
        }

        #region Helpers
        //Redirects to the original URL if it was part of this site
        //Otherwise redirects to the home page
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "GameReviews");
            }
        }

        public enum ManageMessageId
        {
            ChangePasswordSuccess,
            SetPasswordSuccess,
            RemoveLoginSuccess,
        }

        //Converts Error Codes to reaable strings (this is part of the generated code.
        private static string ErrorCodeToString(MembershipCreateStatus createStatus)
        {
            // See http://go.microsoft.com/fwlink/?LinkID=177550 for
            // a full list of status codes.
            switch (createStatus)
            {
                case MembershipCreateStatus.DuplicateUserName:
                    return "User name already exists. Please enter a different user name.";

                case MembershipCreateStatus.DuplicateEmail:
                    return "A user name for that e-mail address already exists. Please enter a different e-mail address.";

                case MembershipCreateStatus.InvalidPassword:
                    return "The password provided is invalid. Please enter a valid password value.";

                case MembershipCreateStatus.InvalidEmail:
                    return "The e-mail address provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.InvalidAnswer:
                    return "The password retrieval answer provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.InvalidQuestion:
                    return "The password retrieval question provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.InvalidUserName:
                    return "The user name provided is invalid. Please check the value and try again.";

                case MembershipCreateStatus.ProviderError:
                    return "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

                case MembershipCreateStatus.UserRejected:
                    return "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

                default:
                    return "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.";
            }
        }
        #endregion
    }
}
