//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameReviewWebsiteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamer
    {
        public Gamer()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int GamerId { get; set; }
        public string Name { get; set; }
        public string Biography { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
