// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace GameReviewWebsiteTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertEmptyGameReviewSearch - Use 'AssertEmptyGameReviewSearchExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertEmptyGameReviewSearch()
        {
            #region Variable Declarations
            HtmlCell uIDestinyCell = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane1.UIItemTable.UIDestinyCell;
            #endregion

            // Verify that the 'InnerText' property of 'Destiny' cell equals 'Destiny'
            Assert.AreEqual(this.AssertEmptyGameReviewSearchExpectedValues.UIDestinyCellInnerText, uIDestinyCell.InnerText);
        }
        
        /// <summary>
        /// AssertLong - Use 'AssertLongExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertLong()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane.UIItemCustom;
            #endregion

            // Verify that the 'InnerText' property of custom control equals 'Game Reviews!
            //
            //  
            //
            //You are searching for zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
            //Search is limited to 50 characters 
            //
            //Game Review Tite 
            //
            //Game Name 
            //
            //Rating '
            Assert.AreEqual(this.AssertLongExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText);
        }
        
        /// <summary>
        /// clicksite - Use 'clicksiteExpectedValues' to pass parameters into this method.
        /// </summary>
        public void clicksite()
        {
            #region Variable Declarations
            HtmlHyperlink uIDoubleDownHyperlink = this.UIGamersGameReviewSiteWindow.UIGamersGameReviewSiteDocument.UIBodyPane1.UIDoubleDownHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'DoubleDown' link equals 'DoubleDown'
            Assert.AreEqual(this.clicksiteExpectedValues.UIDoubleDownHyperlinkInnerText, uIDoubleDownHyperlink.InnerText);
        }
        
        /// <summary>
        /// closeit
        /// </summary>
        public void closeit()
        {
            #region Variable Declarations
            BrowserWindow uIGameReviewsGameRevieWindow1 = this.UIGameReviewsGameRevieWindow1;
            #endregion

            // Perform Close on Browser Window
            uIGameReviewsGameRevieWindow1.Close();
        }
        
        /// <summary>
        /// closesite
        /// </summary>
        public void closesite()
        {
            #region Variable Declarations
            BrowserWindow uIGamersGameReviewSiteWindow = this.UIGamersGameReviewSiteWindow;
            #endregion

            // Perform Close on Browser Window
            uIGamersGameReviewSiteWindow.Close();
        }
        
        /// <summary>
        /// closesite1
        /// </summary>
        public void closesite1()
        {
            #region Variable Declarations
            BrowserWindow uIGameReviewsGameRevieWindow1 = this.UIGameReviewsGameRevieWindow1;
            #endregion

            // Perform Close on Browser Window
            uIGameReviewsGameRevieWindow1.Close();
        }
        
        /// <summary>
        /// OpenSite - Use 'OpenSiteParams' to pass parameters into this method.
        /// </summary>
        public void OpenSite()
        {

            // Go to web page 'http://localhost:3085/' using new browser instance
            this.UIGameReviewsGameRevieWindow1.LaunchUrl(new System.Uri(this.OpenSiteParams.UIGameReviewsGameRevieWindow1Url));
        }
        
        /// <summary>
        /// OpenSite1 - Use 'OpenSite1Params' to pass parameters into this method.
        /// </summary>
        public void OpenSite1()
        {

            // Go to web page 'http://localhost:3085/' using new browser instance
            this.UIGameReviewsGameRevieWindow1.LaunchUrl(new System.Uri(this.OpenSite1Params.UIGameReviewsGameRevieWindow1Url));
        }
        
        /// <summary>
        /// OpenSite2 - Use 'OpenSite2Params' to pass parameters into this method.
        /// </summary>
        public void OpenSite2()
        {
            #region Variable Declarations
            WinMenuItem uIItemMenuItem = this.UIGameReviewsGameRevieWindow1.UIAddressComboControlToolBar.UIItemMenuItem;
            BrowserWindow uIGameReviewsGameRevieWindow1 = this.UIGameReviewsGameRevieWindow1;
            #endregion

            // Go to web page 'http://www.google.com/' using new browser instance
            this.UIGameReviewsGameRevieWindow1.LaunchUrl(new System.Uri(this.OpenSite2Params.UIGameReviewsGameRevieWindow1Url));

            // Click menu item numbered 2 in 'Address Combo Control' menu item
            Mouse.Click(uIItemMenuItem, new Point(215, 4));

            // Go to web page 'http://localhost:3085/'
            uIGameReviewsGameRevieWindow1.NavigateToUrl(new System.Uri(this.OpenSite2Params.UIGameReviewsGameRevieWindow1Url1));
        }
        
        /// <summary>
        /// QuerySubmit
        /// </summary>
        public void QuerySubmit()
        {
            #region Variable Declarations
            HtmlInputButton uISubmitQueryButton = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane1.UISubmitQueryButton;
            #endregion

            // Click 'Submit Query' button
            Mouse.Click(uISubmitQueryButton, new Point(75, 7));
        }
        
        /// <summary>
        /// SubmitDouble
        /// </summary>
        public void SubmitDouble()
        {
            #region Variable Declarations
            HtmlInputButton uISubmitQueryButton = this.UIGamersGameReviewSiteWindow.UIGamersGameReviewSiteDocument.UIBodyPane.UISubmitQueryButton;
            #endregion

            // Click 'Submit Query' button
            Mouse.Click(uISubmitQueryButton, new Point(75, 17));
        }
        
        /// <summary>
        /// Submitit
        /// </summary>
        public void Submitit()
        {
            #region Variable Declarations
            HtmlInputButton uISubmitQueryButton = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane1.UISubmitQueryButton;
            #endregion

            // Click 'Submit Query' button
            Mouse.Click(uISubmitQueryButton, new Point(75, 23));
        }
        
        /// <summary>
        /// SubmitLol
        /// </summary>
        public void SubmitLol()
        {
            #region Variable Declarations
            HtmlInputButton uISubmitQueryButton = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane1.UISubmitQueryButton;
            #endregion

            // Click 'Submit Query' button
            Mouse.Click(uISubmitQueryButton, new Point(72, 8));
        }
        
        /// <summary>
        /// SwitchToGamers
        /// </summary>
        public void SwitchToGamers()
        {
            #region Variable Declarations
            HtmlHyperlink uIGamersHyperlink = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIMenuCustom.UIGamersHyperlink;
            #endregion

            // Click 'Gamers' link
            Mouse.Click(uIGamersHyperlink, new Point(36, 15));
        }
        
        /// <summary>
        /// testlol - Use 'testlolExpectedValues' to pass parameters into this method.
        /// </summary>
        public void testlol()
        {
            #region Variable Declarations
            HtmlHyperlink uILOLHyperlink = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane.UILOLHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'LOL' link equals 'LOL'
            Assert.AreEqual(this.testlolExpectedValues.UILOLHyperlinkInnerText, uILOLHyperlink.InnerText);
        }
        
        /// <summary>
        /// toobigtest - Use 'toobigtestParams' to pass parameters into this method.
        /// </summary>
        public void toobigtest()
        {
            #region Variable Declarations
            HtmlEdit uISearchEdit = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UISearchEdit;
            #endregion

            // Type '444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444' in 'search' text box
            uISearchEdit.Text = this.toobigtestParams.UISearchEditText;
        }
        
        /// <summary>
        /// TypeGamerName - Use 'TypeGamerNameParams' to pass parameters into this method.
        /// </summary>
        public void TypeGamerName()
        {
            #region Variable Declarations
            HtmlEdit uISearchEdit = this.UIGamersGameReviewSiteWindow.UIGamersGameReviewSiteDocument.UISearchEdit;
            #endregion

            // Type 'Double' in 'search' text box
            uISearchEdit.Text = this.TypeGamerNameParams.UISearchEditText;
        }
        
        /// <summary>
        /// typelol - Use 'typelolParams' to pass parameters into this method.
        /// </summary>
        public void typelol()
        {
            #region Variable Declarations
            HtmlEdit uISearchEdit = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UISearchEdit;
            #endregion

            // Type 'lol' in 'search' text box
            uISearchEdit.Text = this.typelolParams.UISearchEditText;
        }
        
        /// <summary>
        /// AssertWrongReview - Use 'AssertWrongReviewExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertWrongReview()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIGameReviewsGameRevieWindow1.UIGameReviewsGameRevieDocument.UIBodyPane.UIItemCustom;
            #endregion

            // Verify that the 'InnerText' property of custom control equals 'Game Reviews!
            //
            //  
            //
            //You are searching for pickles34
            // 
            //
            //Game Review Tite 
            //
            //Game Name 
            //
            //Rating '
            Assert.AreEqual(this.AssertWrongReviewExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText);
        }
        
        #region Properties
        public virtual AssertEmptyGameReviewSearchExpectedValues AssertEmptyGameReviewSearchExpectedValues
        {
            get
            {
                if ((this.mAssertEmptyGameReviewSearchExpectedValues == null))
                {
                    this.mAssertEmptyGameReviewSearchExpectedValues = new AssertEmptyGameReviewSearchExpectedValues();
                }
                return this.mAssertEmptyGameReviewSearchExpectedValues;
            }
        }
        
        public virtual AssertLongExpectedValues AssertLongExpectedValues
        {
            get
            {
                if ((this.mAssertLongExpectedValues == null))
                {
                    this.mAssertLongExpectedValues = new AssertLongExpectedValues();
                }
                return this.mAssertLongExpectedValues;
            }
        }
        
        public virtual clicksiteExpectedValues clicksiteExpectedValues
        {
            get
            {
                if ((this.mclicksiteExpectedValues == null))
                {
                    this.mclicksiteExpectedValues = new clicksiteExpectedValues();
                }
                return this.mclicksiteExpectedValues;
            }
        }
        
        public virtual OpenSiteParams OpenSiteParams
        {
            get
            {
                if ((this.mOpenSiteParams == null))
                {
                    this.mOpenSiteParams = new OpenSiteParams();
                }
                return this.mOpenSiteParams;
            }
        }
        
        public virtual OpenSite1Params OpenSite1Params
        {
            get
            {
                if ((this.mOpenSite1Params == null))
                {
                    this.mOpenSite1Params = new OpenSite1Params();
                }
                return this.mOpenSite1Params;
            }
        }
        
        public virtual OpenSite2Params OpenSite2Params
        {
            get
            {
                if ((this.mOpenSite2Params == null))
                {
                    this.mOpenSite2Params = new OpenSite2Params();
                }
                return this.mOpenSite2Params;
            }
        }
        
        public virtual testlolExpectedValues testlolExpectedValues
        {
            get
            {
                if ((this.mtestlolExpectedValues == null))
                {
                    this.mtestlolExpectedValues = new testlolExpectedValues();
                }
                return this.mtestlolExpectedValues;
            }
        }
        
        public virtual toobigtestParams toobigtestParams
        {
            get
            {
                if ((this.mtoobigtestParams == null))
                {
                    this.mtoobigtestParams = new toobigtestParams();
                }
                return this.mtoobigtestParams;
            }
        }
        
        public virtual TypeGamerNameParams TypeGamerNameParams
        {
            get
            {
                if ((this.mTypeGamerNameParams == null))
                {
                    this.mTypeGamerNameParams = new TypeGamerNameParams();
                }
                return this.mTypeGamerNameParams;
            }
        }
        
        public virtual typelolParams typelolParams
        {
            get
            {
                if ((this.mtypelolParams == null))
                {
                    this.mtypelolParams = new typelolParams();
                }
                return this.mtypelolParams;
            }
        }
        
        public virtual AssertWrongReviewExpectedValues AssertWrongReviewExpectedValues
        {
            get
            {
                if ((this.mAssertWrongReviewExpectedValues == null))
                {
                    this.mAssertWrongReviewExpectedValues = new AssertWrongReviewExpectedValues();
                }
                return this.mAssertWrongReviewExpectedValues;
            }
        }
        
        public UIGameReviewsGameRevieWindow UIGameReviewsGameRevieWindow
        {
            get
            {
                if ((this.mUIGameReviewsGameRevieWindow == null))
                {
                    this.mUIGameReviewsGameRevieWindow = new UIGameReviewsGameRevieWindow();
                }
                return this.mUIGameReviewsGameRevieWindow;
            }
        }
        
        public UIGameReviewsGameRevieWindow1 UIGameReviewsGameRevieWindow1
        {
            get
            {
                if ((this.mUIGameReviewsGameRevieWindow1 == null))
                {
                    this.mUIGameReviewsGameRevieWindow1 = new UIGameReviewsGameRevieWindow1();
                }
                return this.mUIGameReviewsGameRevieWindow1;
            }
        }
        
        public UIGamersGameReviewSiteWindow UIGamersGameReviewSiteWindow
        {
            get
            {
                if ((this.mUIGamersGameReviewSiteWindow == null))
                {
                    this.mUIGamersGameReviewSiteWindow = new UIGamersGameReviewSiteWindow();
                }
                return this.mUIGamersGameReviewSiteWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertEmptyGameReviewSearchExpectedValues mAssertEmptyGameReviewSearchExpectedValues;
        
        private AssertLongExpectedValues mAssertLongExpectedValues;
        
        private clicksiteExpectedValues mclicksiteExpectedValues;
        
        private OpenSiteParams mOpenSiteParams;
        
        private OpenSite1Params mOpenSite1Params;
        
        private OpenSite2Params mOpenSite2Params;
        
        private testlolExpectedValues mtestlolExpectedValues;
        
        private toobigtestParams mtoobigtestParams;
        
        private TypeGamerNameParams mTypeGamerNameParams;
        
        private typelolParams mtypelolParams;
        
        private AssertWrongReviewExpectedValues mAssertWrongReviewExpectedValues;
        
        private UIGameReviewsGameRevieWindow mUIGameReviewsGameRevieWindow;
        
        private UIGameReviewsGameRevieWindow1 mUIGameReviewsGameRevieWindow1;
        
        private UIGamersGameReviewSiteWindow mUIGamersGameReviewSiteWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertEmptyGameReviewSearch'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class AssertEmptyGameReviewSearchExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Destiny' cell equals 'Destiny'
        /// </summary>
        public string UIDestinyCellInnerText = "Destiny";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertLong'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class AssertLongExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'Game Reviews!
        ///
        ///  
        ///
        ///You are searching for zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
        ///Search is limited to 50 characters 
        ///
        ///Game Review Tite 
        ///
        ///Game Name 
        ///
        ///Rating '
        /// </summary>
        public string UIItemCustomInnerText = "Game Reviews!\r\n\r\n  \r\n\r\nYou are searching for zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz" +
            "zzzzzzzzzzzzzz\r\nSearch is limited to 50 characters \r\n\r\nGame Review Tite \r\n\r\nGame" +
            " Name \r\n\r\nRating ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'clicksite'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class clicksiteExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'DoubleDown' link equals 'DoubleDown'
        /// </summary>
        public string UIDoubleDownHyperlinkInnerText = "DoubleDown";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenSite'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class OpenSiteParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:3085/' using new browser instance
        /// </summary>
        public string UIGameReviewsGameRevieWindow1Url = "http://localhost:3085/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenSite1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class OpenSite1Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:3085/' using new browser instance
        /// </summary>
        public string UIGameReviewsGameRevieWindow1Url = "http://localhost:3085/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'OpenSite2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class OpenSite2Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://www.google.com/' using new browser instance
        /// </summary>
        public string UIGameReviewsGameRevieWindow1Url = "http://www.google.com/";
        
        /// <summary>
        /// Go to web page 'http://localhost:3085/'
        /// </summary>
        public string UIGameReviewsGameRevieWindow1Url1 = "http://localhost:3085/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'testlol'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class testlolExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'LOL' link equals 'LOL'
        /// </summary>
        public string UILOLHyperlinkInnerText = "LOL";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'toobigtest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class toobigtestParams
    {
        
        #region Fields
        /// <summary>
        /// Type '444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444' in 'search' text box
        /// </summary>
        public string UISearchEditText = @"444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TypeGamerName'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TypeGamerNameParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Double' in 'search' text box
        /// </summary>
        public string UISearchEditText = "Double";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'typelol'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class typelolParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'lol' in 'search' text box
        /// </summary>
        public string UISearchEditText = "lol";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertWrongReview'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class AssertWrongReviewExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'Game Reviews!
        ///
        ///  
        ///
        ///You are searching for pickles34
        /// 
        ///
        ///Game Review Tite 
        ///
        ///Game Name 
        ///
        ///Rating '
        /// </summary>
        public string UIItemCustomInnerText = "Game Reviews!\r\n\r\n  \r\n\r\nYou are searching for pickles34\r\n \r\n\r\nGame Review Tite \r\n\r" +
            "\nGame Name \r\n\r\nRating ";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGameReviewsGameRevieWindow : WinWindow
    {
        
        public UIGameReviewsGameRevieWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Game Reviews - Game Review Site! - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Game Reviews - Game Review Site! - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIGameReviewsGameRevieClient UIGameReviewsGameRevieClient
        {
            get
            {
                if ((this.mUIGameReviewsGameRevieClient == null))
                {
                    this.mUIGameReviewsGameRevieClient = new UIGameReviewsGameRevieClient(this);
                }
                return this.mUIGameReviewsGameRevieClient;
            }
        }
        
        public UIItemDocument UIItemDocument
        {
            get
            {
                if ((this.mUIItemDocument == null))
                {
                    this.mUIItemDocument = new UIItemDocument(this);
                }
                return this.mUIItemDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGameReviewsGameRevieClient mUIGameReviewsGameRevieClient;
        
        private UIItemDocument mUIItemDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGameReviewsGameRevieClient : WinClient
    {
        
        public UIGameReviewsGameRevieClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Game Reviews - Game Review Site! - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Game Reviews - Game Review Site! - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemDocument : WinControl
    {
        
        public UIItemDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Game Reviews - Game Review Site! - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WinCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.WindowTitles.Add("Game Reviews - Game Review Site! - Google Chrome");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WinCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGameReviewsGameRevieWindow1 : BrowserWindow
    {
        
        public UIGameReviewsGameRevieWindow1()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Game Reviews - Game Review Site!";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Game Reviews - Game Review Site!");
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGameReviewsGameRevieDocument UIGameReviewsGameRevieDocument
        {
            get
            {
                if ((this.mUIGameReviewsGameRevieDocument == null))
                {
                    this.mUIGameReviewsGameRevieDocument = new UIGameReviewsGameRevieDocument(this);
                }
                return this.mUIGameReviewsGameRevieDocument;
            }
        }
        
        public UIGoogleDocument UIGoogleDocument
        {
            get
            {
                if ((this.mUIGoogleDocument == null))
                {
                    this.mUIGoogleDocument = new UIGoogleDocument(this);
                }
                return this.mUIGoogleDocument;
            }
        }
        
        public UIAddressComboControlToolBar UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        #endregion
        
        #region Fields
        private UIGameReviewsGameRevieDocument mUIGameReviewsGameRevieDocument;
        
        private UIGoogleDocument mUIGoogleDocument;
        
        private UIAddressComboControlToolBar mUIAddressComboControlToolBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGameReviewsGameRevieDocument : HtmlDocument
    {
        
        public UIGameReviewsGameRevieDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Game Reviews - Game Review Site!";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3085/";
            this.WindowTitles.Add("Game Reviews - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public UIBodyPane UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane(this);
                }
                return this.mUIBodyPane;
            }
        }
        
        public HtmlEdit UISearchEdit
        {
            get
            {
                if ((this.mUISearchEdit == null))
                {
                    this.mUISearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "search";
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "search";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"search\" id=\"search\" type=\"text\" va";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISearchEdit.WindowTitles.Add("Game Reviews - Game Review Site!");
                    #endregion
                }
                return this.mUISearchEdit;
            }
        }
        
        public UIBodyPane1 UIBodyPane1
        {
            get
            {
                if ((this.mUIBodyPane1 == null))
                {
                    this.mUIBodyPane1 = new UIBodyPane1(this);
                }
                return this.mUIBodyPane1;
            }
        }
        
        public UIMenuCustom UIMenuCustom
        {
            get
            {
                if ((this.mUIMenuCustom == null))
                {
                    this.mUIMenuCustom = new UIMenuCustom(this);
                }
                return this.mUIMenuCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIBodyPane mUIBodyPane;
        
        private HtmlEdit mUISearchEdit;
        
        private UIBodyPane1 mUIBodyPane1;
        
        private UIMenuCustom mUIMenuCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBodyPane : HtmlDiv
    {
        
        public UIBodyPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Game Reviews!\r\n\r\n  \r\n\r\nYou are searching";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("Game Reviews - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "SECTION";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "content-wrapper main-content clear-fix";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"content-wrapper main-content clea";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Game Reviews - Game Review Site!");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlHyperlink UILOLHyperlink
        {
            get
            {
                if ((this.mUILOLHyperlink == null))
                {
                    this.mUILOLHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILOLHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILOLHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILOLHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILOLHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "LOL";
                    this.mUILOLHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/GameReviews/Details/3";
                    this.mUILOLHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILOLHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3085/GameReviews/Details/3";
                    this.mUILOLHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILOLHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/GameReviews/Details/3\"";
                    this.mUILOLHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUILOLHyperlink.WindowTitles.Add("Game Reviews - Game Review Site!");
                    #endregion
                }
                return this.mUILOLHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlHyperlink mUILOLHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBodyPane1 : HtmlDiv
    {
        
        public UIBodyPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Game Reviews!\r\n\r\n  \r\n\r\n\r\nGame Review Tit";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("Game Reviews - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UISubmitQueryButton
        {
            get
            {
                if ((this.mUISubmitQueryButton == null))
                {
                    this.mUISubmitQueryButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Submit Query";
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "type=\"submit\" value=\"Submit Query\"";
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUISubmitQueryButton.WindowTitles.Add("Game Reviews - Game Review Site!");
                    #endregion
                }
                return this.mUISubmitQueryButton;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUISubmitQueryButton;
        
        private UIItemTable mUIItemTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Game Review Tite \r\n\r\nGame Name \r\n\r\nRatin";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = null;
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "21";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "3";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Game Reviews - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIDestinyCell
        {
            get
            {
                if ((this.mUIDestinyCell == null))
                {
                    this.mUIDestinyCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIDestinyCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIDestinyCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIDestinyCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIDestinyCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Destiny";
                    this.mUIDestinyCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIDestinyCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIDestinyCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIDestinyCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIDestinyCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUIDestinyCell.WindowTitles.Add("Game Reviews - Game Review Site!");
                    #endregion
                }
                return this.mUIDestinyCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIDestinyCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMenuCustom : HtmlCustom
    {
        
        public UIMenuCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "menu";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"menu\"";
            this.FilterProperties["TagInstance"] = "2";
            this.WindowTitles.Add("Game Reviews - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIGamersHyperlink
        {
            get
            {
                if ((this.mUIGamersHyperlink == null))
                {
                    this.mUIGamersHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIGamersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIGamersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIGamersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIGamersHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Gamers";
                    this.mUIGamersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Gamers";
                    this.mUIGamersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIGamersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3085/Gamers";
                    this.mUIGamersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIGamersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Gamers\"";
                    this.mUIGamersHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIGamersHyperlink.WindowTitles.Add("Game Reviews - Game Review Site!");
                    #endregion
                }
                return this.mUIGamersHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIGamersHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGoogleDocument : HtmlDocument
    {
        
        public UIGoogleDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "gsr";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Google";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://www.google.com/?gws_rd=ssl";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public UIGBPane UIGBPane
        {
            get
            {
                if ((this.mUIGBPane == null))
                {
                    this.mUIGBPane = new UIGBPane(this);
                }
                return this.mUIGBPane;
            }
        }
        #endregion
        
        #region Fields
        private UIGBPane mUIGBPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGBPane : HtmlDiv
    {
        
        public UIGBPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "gb";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Come here often? Make Google your homepa";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "gb_Mc gb_Tc gb_wb";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"gb_Mc gb_Tc gb_wb\" id=\"gb\" style=\"min-width: 980px;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "9";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIYouGmailImagesPane
        {
            get
            {
                if ((this.mUIYouGmailImagesPane == null))
                {
                    this.mUIYouGmailImagesPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIYouGmailImagesPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIYouGmailImagesPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIYouGmailImagesPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "+You\r\n\r\nGmail\r\n\r\nImages\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n+";
                    this.mUIYouGmailImagesPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIYouGmailImagesPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "gb_0 gb_Qc gb_f gb_Pc gb_Tc";
                    this.mUIYouGmailImagesPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"gb_0 gb_Qc gb_f gb_Pc gb_Tc\" style=\"min-width: 295px;\"";
                    this.mUIYouGmailImagesPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
                    this.mUIYouGmailImagesPane.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIYouGmailImagesPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIYouGmailImagesPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAddressComboControlToolBar : WinToolBar
    {
        
        public UIAddressComboControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("Google");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIItemMenuItem
        {
            get
            {
                if ((this.mUIItemMenuItem == null))
                {
                    this.mUIItemMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIItemMenuItem.SearchProperties[WinMenuItem.PropertyNames.Instance] = "2";
                    this.mUIItemMenuItem.WindowTitles.Add("Google");
                    #endregion
                }
                return this.mUIItemMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIItemMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGamersGameReviewSiteWindow : BrowserWindow
    {
        
        public UIGamersGameReviewSiteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Gamers - Game Review Site!";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Gamers - Game Review Site!");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGamersGameReviewSiteDocument UIGamersGameReviewSiteDocument
        {
            get
            {
                if ((this.mUIGamersGameReviewSiteDocument == null))
                {
                    this.mUIGamersGameReviewSiteDocument = new UIGamersGameReviewSiteDocument(this);
                }
                return this.mUIGamersGameReviewSiteDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGamersGameReviewSiteDocument mUIGamersGameReviewSiteDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIGamersGameReviewSiteDocument : HtmlDocument
    {
        
        public UIGamersGameReviewSiteDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Gamers - Game Review Site!";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Gamers";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3085/Gamers";
            this.WindowTitles.Add("Gamers - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UISearchEdit
        {
            get
            {
                if ((this.mUISearchEdit == null))
                {
                    this.mUISearchEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "search";
                    this.mUISearchEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "search";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"search\" id=\"search\" type=\"text\" va";
                    this.mUISearchEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUISearchEdit.WindowTitles.Add("Gamers - Game Review Site!");
                    #endregion
                }
                return this.mUISearchEdit;
            }
        }
        
        public UIBodyPane2 UIBodyPane
        {
            get
            {
                if ((this.mUIBodyPane == null))
                {
                    this.mUIBodyPane = new UIBodyPane2(this);
                }
                return this.mUIBodyPane;
            }
        }
        
        public UIBodyPane11 UIBodyPane1
        {
            get
            {
                if ((this.mUIBodyPane1 == null))
                {
                    this.mUIBodyPane1 = new UIBodyPane11(this);
                }
                return this.mUIBodyPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUISearchEdit;
        
        private UIBodyPane2 mUIBodyPane;
        
        private UIBodyPane11 mUIBodyPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBodyPane2 : HtmlDiv
    {
        
        public UIBodyPane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Gamers\r\n\r\n  \r\n\r\n\r\nName \r\n\r\nAvatarUrl \r\n\r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("Gamers - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UISubmitQueryButton
        {
            get
            {
                if ((this.mUISubmitQueryButton == null))
                {
                    this.mUISubmitQueryButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Submit Query";
                    this.mUISubmitQueryButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "type=\"submit\" value=\"Submit Query\"";
                    this.mUISubmitQueryButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUISubmitQueryButton.WindowTitles.Add("Gamers - Game Review Site!");
                    #endregion
                }
                return this.mUISubmitQueryButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUISubmitQueryButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIBodyPane11 : HtmlDiv
    {
        
        public UIBodyPane11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "body";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Gamers\r\n\r\n  \r\n\r\nYou are searching for Do";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"body\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
            this.WindowTitles.Add("Gamers - Game Review Site!");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIDoubleDownHyperlink
        {
            get
            {
                if ((this.mUIDoubleDownHyperlink == null))
                {
                    this.mUIDoubleDownHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDoubleDownHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDoubleDownHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDoubleDownHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDoubleDownHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "DoubleDown";
                    this.mUIDoubleDownHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Gamers/Details/9";
                    this.mUIDoubleDownHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDoubleDownHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3085/Gamers/Details/9";
                    this.mUIDoubleDownHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDoubleDownHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Gamers/Details/9\"";
                    this.mUIDoubleDownHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIDoubleDownHyperlink.WindowTitles.Add("Gamers - Game Review Site!");
                    #endregion
                }
                return this.mUIDoubleDownHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIDoubleDownHyperlink;
        #endregion
    }
}
