//Chris Lucian & Chad Davies
//CS 643 Advanced Databases
//11/8/2014

using System.ComponentModel.DataAnnotations;

namespace GameReviewWebsiteProject.Models
{
    //This class uses the partial keyword in order to augment the class
    //Generated by the code generator
    //This class allows us to assign meta data to a class
    //Which is then interpreted by the automatic features of MVC and .Net
    [MetadataType(typeof(AuthorMetaData))]
    public partial class Author
    {

        //The required attribute shows us that the field is not nullable in the database
        //The string length attribute shows the max length of the string
        //These attributes are used to automatically generate validation code when they are used in the system
        public class AuthorMetaData
        {
            public int AuthorId { get; set; }
            [StringLength(150)]
            [Required]
            public string Name { get; set; }
            [Required]
            [StringLength(150)]
            public string Genre { get; set; }
            [Required]
            [StringLength(4000)]
            public string Biography { get; set; }
        }
    }
}
