//Chris Lucian & Chad Davies
//CS 643 Advanced Databases
//11/8/2014

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GameReviewWebsiteProject.Models
{
    //This class uses the partial keyword in order to augment the class
    //Generated by the code generator
    //This class allows us to assign meta data to a class
    //Which is then interpreted by the automatic features of MVC and .Net
    [MetadataType(typeof(GameMetaData))]
    public partial class Game
    {
        //The required attribute shows us that the field is not nullable in the database
        //The string length attribute shows the max length of the string
        //These attributes are used to automatically generate validation code when they are used in the system
        public class GameMetaData
        {
            public int GameId { get; set; }
            [Required]
            [StringLength(150)]
            public string Title { get; set; }
            [Required]
            [StringLength(4000)]
            public string Description { get; set; }

            public virtual ICollection<GameReview> GameReviews { get; set; }
        }
    }
}
