//Chris Lucian & Chad Davies
//CS 643 Advanced Databases
//11/8/2014

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GameReviewWebsiteProject.Models
{
    //This class uses the partial keyword in order to augment the class
    //Generated by the code generator
    //This class allows us to assign meta data to a class
    //Which is then interpreted by the automatic features of MVC and .Net
    [MetadataType(typeof(GameReviewMetaData))]
    public partial class GameReview
    {
        //The required attribute shows us that the field is not nullable in the database
        //The string length attribute shows the max length of the string
        //These attributes are used to automatically generate validation code when they are used in the system
        //The Range Attribute is used to shwo a field can only exist within a range
        public class GameReviewMetaData
        {
            public int GameReviewId { get; set; }
            [Required]
            public int GameId { get; set; }
            [Required]
            public int AuthorId { get; set; }
            [Required]
            [StringLength(150)]
            public string Title { get; set; }
            [Required]
            [StringLength(4000)]
            public string Content { get; set; }
            [Required]
            [Range(typeof(Decimal), "1.0", "5.0")]
            public decimal Rating { get; set; }

            public virtual Author Author { get; set; }
            public virtual ICollection<Comment> Comments { get; set; }
            public virtual Game Game { get; set; }
        }
    }
}
